# Generated by Django 5.2.8 on 2025-11-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        ('pantry', '0074_delete_lifeskillscoach_delete_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervalidationlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.product'),
        ),
    ]
