# Generated by Django 5.2.10 on 2026-01-15 02:19

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


def migrate_email_type_to_fk(apps, schema_editor):
    """
    Migrate existing EmailLog records from string email_type to FK.
    This runs after EmailType records are created by 0005_seed_email_types.
    """
    EmailLog = apps.get_model('log', 'EmailLog')
    EmailType = apps.get_model('log', 'EmailType')
    
    # Build lookup of email type name -> id
    email_type_map = {et.name: et.id for et in EmailType.objects.all()}
    
    # Update each EmailLog to set the new FK field
    for log in EmailLog.objects.all():
        old_type = log.email_type_old
        if old_type and old_type in email_type_map:
            log.email_type_id = email_type_map[old_type]
            log.save(update_fields=['email_type_id'])


def reverse_migrate_email_type(apps, schema_editor):
    """Reverse: copy FK back to string field."""
    EmailLog = apps.get_model('log', 'EmailLog')
    EmailType = apps.get_model('log', 'EmailType')
    
    email_type_map = {et.id: et.name for et in EmailType.objects.all()}
    
    for log in EmailLog.objects.all():
        if log.email_type_id and log.email_type_id in email_type_map:
            log.email_type_old = email_type_map[log.email_type_id]
            log.save(update_fields=['email_type_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_initial'),
    ]

    operations = [
        # Step 1: Create EmailType model
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Internal identifier (e.g., 'onboarding', 'password_reset')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'New User Onboarding')", max_length=255)),
                ('subject', models.CharField(help_text='Email subject line (supports template variables like {{ user.first_name }})', max_length=255)),
                ('html_template', models.CharField(blank=True, help_text="Path to HTML template file (e.g., 'registration/new_user_onboarding.html')", max_length=255)),
                ('text_template', models.CharField(blank=True, help_text="Path to text template file (e.g., 'registration/new_user_onboarding.txt')", max_length=255)),
                ('html_content', tinymce.models.HTMLField(blank=True, help_text='HTML email content (editable). Takes priority over template file.')),
                ('text_content', models.TextField(blank=True, help_text='Plain text email content. Takes priority over template file.')),
                ('from_email', models.EmailField(blank=True, help_text='From email address (leave blank to use global default)', max_length=254)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to email address (leave blank to use global default)', max_length=254)),
                ('available_variables', models.TextField(blank=True, help_text='Documentation of available template variables for this email type')),
                ('description', models.TextField(blank=True, help_text='Description of when this email is sent and its purpose')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable sending of this email type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Type',
                'verbose_name_plural': 'Email Types',
                'ordering': ['display_name'],
            },
        ),
        
        # Step 2: Update EmailLog model options
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        
        # Step 3: Add new fields to EmailLog
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if the email failed to send'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, help_text='The rendered subject at time of sending', max_length=255),
        ),
        
        # Step 4: Rename old email_type column to preserve data
        migrations.RenameField(
            model_name='emaillog',
            old_name='email_type',
            new_name='email_type_old',
        ),
        
        # Step 5: Add new FK field (nullable initially)
        migrations.AddField(
            model_name='emaillog',
            name='email_type',
            field=models.ForeignKey(
                null=True,  # Allow null temporarily during migration
                blank=True,
                help_text='The type of email that was sent',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='logs',
                to='log.emailtype'
            ),
        ),
    ]
