# Generated by Django 5.2.10 on 2026-01-15 02:19

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Internal identifier (e.g., 'onboarding', 'password_reset')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'New User Onboarding')", max_length=255)),
                ('subject', models.CharField(help_text='Email subject line (supports template variables like {{ user.first_name }})', max_length=255)),
                ('html_template', models.CharField(blank=True, help_text="Path to HTML template file (e.g., 'registration/new_user_onboarding.html')", max_length=255)),
                ('text_template', models.CharField(blank=True, help_text="Path to text template file (e.g., 'registration/new_user_onboarding.txt')", max_length=255)),
                ('html_content', tinymce.models.HTMLField(blank=True, help_text='HTML email content (editable). Takes priority over template file.')),
                ('text_content', models.TextField(blank=True, help_text='Plain text email content. Takes priority over template file.')),
                ('from_email', models.EmailField(blank=True, help_text='From email address (leave blank to use global default)', max_length=254)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to email address (leave blank to use global default)', max_length=254)),
                ('available_variables', models.TextField(blank=True, help_text='Documentation of available template variables for this email type')),
                ('description', models.TextField(blank=True, help_text='Description of when this email is sent and its purpose')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable sending of this email type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Type',
                'verbose_name_plural': 'Email Types',
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if the email failed to send'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, help_text='The rendered subject at time of sending', max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.ForeignKey(help_text='The type of email that was sent', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='log.emailtype'),
        ),
    ]
