# Generated by Django 5.2.10 on 2026-01-15 02:20

from django.db import migrations


ONBOARDING_HTML = '''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Basketful!</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            background-color: #f4f7fa;
            color: #374151;
            padding: 20px;
            margin: 0;
            line-height: 1.6;
        }
        .container {
            background: #ffffff;
            border-radius: 12px;
            padding: 40px;
            max-width: 560px;
            margin: 20px auto;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 28px; margin-bottom: 8px; color: #3b82f6; font-weight: bold; }
        h2 { color: #1f2937; font-size: 24px; font-weight: 600; margin: 0 0 8px 0; }
        .subtitle { color: #6b7280; font-size: 16px; margin: 0; }
        .content { margin: 30px 0; }
        .content p { color: #4b5563; font-size: 16px; margin: 0 0 16px 0; }
        .username-box {
            background: linear-gradient(135deg, #eff6ff 0%, #f0fdf4 100%);
            border: 2px solid #3b82f6;
            border-radius: 12px;
            padding: 24px;
            margin: 28px 0;
            text-align: center;
        }
        .username-label { color: #6b7280; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 8px 0; font-weight: 500; }
        .username-value { color: #1e40af; font-size: 22px; font-weight: 700; margin: 0; font-family: 'SF Mono', Monaco, 'Courier New', monospace; background: #ffffff; padding: 12px 20px; border-radius: 8px; display: inline-block; border: 1px solid #bfdbfe; }
        .username-note { color: #6b7280; font-size: 13px; margin: 12px 0 0 0; }
        .btn-container { text-align: center; margin: 32px 0; }
        .btn { display: inline-block; background-color: #3b82f6; color: #ffffff !important; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px; }
        .btn:hover { background-color: #2563eb; }
        .checklist { background: #f9fafb; border-radius: 8px; padding: 20px 24px; margin: 24px 0; }
        .checklist p { margin: 0 0 8px 0; color: #374151; }
        .checklist p:last-child { margin-bottom: 0; }
        .footer { border-top: 1px solid #e5e7eb; padding-top: 24px; margin-top: 32px; }
        .footer p { color: #9ca3af; font-size: 14px; margin: 0 0 12px 0; }
        .signature { color: #6b7280; font-size: 15px; }
        .signature strong { color: #374151; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">🥕 Basketful</div>
            <h2>Welcome, {{ user.first_name|default:user.username }}!</h2>
            <p class="subtitle">Love Your Neighbor Life Skills Program</p>
        </div>
        <div class="content">
            <p>We're excited to have you join our community! Your Basketful account has been created where you'll place and manage your food orders.</p>
        </div>
        <div class="username-box">
            <p class="username-label">Your Username</p>
            <p class="username-value">{{ user.username }}</p>
            <p class="username-note">📝 Save this! You'll need it to log in.</p>
        </div>
        <div class="content">
            <p>To get started, click the button below to set your password:</p>
        </div>
        <div class="btn-container">
            <a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}" class="btn">Set Your Password</a>
        </div>
        <div class="checklist">
            <p>✓ Sign in to your account</p>
            <p>✓ Place your food orders</p>
            <p>✓ Access program resources</p>
        </div>
        <div class="footer">
            <p>If you didn't request this account or believe this was sent in error, you can safely ignore this email.</p>
            <p class="signature">Thanks,<br><strong>The Basketful Team</strong></p>
        </div>
    </div>
</body>
</html>'''

ONBOARDING_TEXT = '''Welcome to Basketful, {{ user.first_name|default:user.username }}!

Love Your Neighbor Life Skills Program

We're excited to have you join our community!

========================================
YOUR USERNAME: {{ user.username }}
========================================
(Save this - you'll need it to log in)

Set your password here:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Once your account is set up, you'll be able to:
- Sign in to your account
- Place your food orders
- Access program resources

If you didn't request this account, you can safely ignore this email.

Thanks,
The Basketful Team'''

PASSWORD_RESET_HTML = '''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Your Password</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            background-color: #f4f7fa;
            color: #374151;
            padding: 20px;
            margin: 0;
            line-height: 1.6;
        }
        .container { background: #ffffff; border-radius: 12px; padding: 40px; max-width: 560px; margin: 20px auto; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 28px; margin-bottom: 8px; color: #3b82f6; font-weight: bold; }
        h2 { color: #1f2937; font-size: 24px; font-weight: 600; margin: 0 0 8px 0; }
        .subtitle { color: #6b7280; font-size: 16px; margin: 0; }
        .content { margin: 30px 0; }
        .content p { color: #4b5563; font-size: 16px; margin: 0 0 16px 0; }
        .btn-container { text-align: center; margin: 32px 0; }
        .btn { display: inline-block; background-color: #3b82f6; color: #ffffff !important; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px; }
        .btn:hover { background-color: #2563eb; }
        .info-box { background: #f9fafb; border-radius: 8px; padding: 20px 24px; margin: 24px 0; border-left: 4px solid #3b82f6; }
        .info-box p { margin: 0; color: #374151; font-size: 14px; }
        .footer { border-top: 1px solid #e5e7eb; padding-top: 24px; margin-top: 32px; }
        .footer p { color: #9ca3af; font-size: 14px; margin: 0 0 12px 0; }
        .signature { color: #6b7280; font-size: 15px; }
        .signature strong { color: #374151; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">🥕 Basketful</div>
            <h2>Reset Your Password</h2>
            <p class="subtitle">Love Your Neighbor Life Skills Program</p>
        </div>
        <div class="content">
            <p>Hello {{ user.get_username }},</p>
            <p>You're receiving this email because you requested a password reset for your account.</p>
        </div>
        <div class="btn-container">
            <a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}" class="btn">Reset Your Password</a>
        </div>
        <div class="info-box">
            <p>This link will expire after use. If you didn't request a password reset, you can safely ignore this email.</p>
        </div>
        <div class="footer">
            <p>If the button above doesn't work, copy and paste this link into your browser:</p>
            <p style="word-break: break-all; color: #3b82f6;">{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}</p>
            <p class="signature">Thanks,<br><strong>The Basketful Team</strong></p>
        </div>
    </div>
</body>
</html>'''

PASSWORD_RESET_TEXT = '''Hello {{ user.get_username }},

You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If you didn't request a password reset, you can ignore this email.

Thanks,
{{ site_name }} team'''


def seed_email_types(apps, schema_editor):
    """Create initial EmailType records with content from existing templates."""
    EmailType = apps.get_model('log', 'EmailType')
    
    # Clear any existing email types (fresh start)
    EmailType.objects.all().delete()
    
    # Onboarding email
    EmailType.objects.create(
        name='onboarding',
        display_name='New User Onboarding',
        subject='Welcome to Love Your Neighbor!',
        html_template='registration/new_user_onboarding.html',
        text_template='registration/new_user_onboarding.txt',
        html_content=ONBOARDING_HTML,
        text_content=ONBOARDING_TEXT,
        reply_to='elizabethp@lovewm.org',
        available_variables='{{ user.first_name }}, {{ user.username }}, {{ user.email }}, {{ domain }}, {{ protocol }}, {{ uid }}, {{ token }}',
        description='Sent to new users when their account is created. Contains username and password reset link.',
        is_active=True,
    )
    
    # Password reset email
    EmailType.objects.create(
        name='password_reset',
        display_name='Password Reset',
        subject='Set Your Password',
        html_template='registration/password_reset_email.html',
        text_template='registration/password_reset_email.txt',
        html_content=PASSWORD_RESET_HTML,
        text_content=PASSWORD_RESET_TEXT,
        reply_to='it@loveyourneighbor.org',
        available_variables='{{ user.get_username }}, {{ user.email }}, {{ site_name }}, {{ domain }}, {{ protocol }}, {{ uid }}, {{ token }}',
        description='Sent when a user requests a password reset or admin resets their password.',
        is_active=True,
    )
    
    # Placeholder for future email types
    EmailType.objects.create(
        name='order_confirmation',
        display_name='Order Confirmation',
        subject='Your Order Has Been Placed',
        html_template='',
        text_template='',
        html_content='',
        text_content='',
        reply_to='',
        available_variables='{{ user.first_name }}, {{ order.id }}, {{ order.total }}, {{ order.items }}',
        description='Sent when a participant places an order. (Not yet implemented)',
        is_active=False,
    )
    
    EmailType.objects.create(
        name='voucher_notification',
        display_name='Voucher Notification',
        subject='You Have a New Voucher',
        html_template='',
        text_template='',
        html_content='',
        text_content='',
        reply_to='',
        available_variables='{{ user.first_name }}, {{ voucher.code }}, {{ voucher.amount }}',
        description='Sent when a voucher is issued to a participant. (Not yet implemented)',
        is_active=False,
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded EmailType records."""
    EmailType = apps.get_model('log', 'EmailType')
    EmailType.objects.filter(
        name__in=['onboarding', 'password_reset', 'order_confirmation', 'voucher_notification']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_emailtype_alter_emaillog_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_email_types, reverse_seed),
    ]
