# Generated by Django 5.2.10 on 2026-01-15 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_seed_email_types'),
    ]

    operations = [
        # Step 1: Remove the old string-based email_type column
        migrations.RemoveField(
            model_name='emaillog',
            name='email_type_old',
        ),
        
        # Step 2: Make email_type FK non-nullable (data is migrated)
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.ForeignKey(
                help_text='The type of email that was sent',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='logs',
                to='log.emailtype'
            ),
        ),
    ]
