# Generated by Django 5.2.10 on 2026-02-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_add_go_fresh_settings'),
        ('log', '0007_userloginlog'),
        ('orders', '0008_add_go_fresh_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraceAllowanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_over', models.DecimalField(decimal_places=2, help_text='Dollar amount over budget', max_digits=6)),
                ('grace_message', models.TextField(help_text='Educational message displayed to participant')),
                ('proceeded', models.BooleanField(default=False, help_text='Whether participant proceeded with order after grace warning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Order associated with grace allowance usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_logs', to='orders.order')),
                ('participant', models.ForeignKey(help_text='Participant who used grace allowance', on_delete=django.db.models.deletion.CASCADE, related_name='grace_logs', to='account.participant')),
            ],
            options={
                'verbose_name': 'Grace Allowance Log',
                'verbose_name_plural': 'Grace Allowance Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='log_graceal_created_e5929c_idx'), models.Index(fields=['participant', '-created_at'], name='log_graceal_partici_a57b04_idx')],
            },
        ),
    ]
