# Generated by Django 5.2.10 on 2026-07-04 18:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_emaillog_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtype',
            name='html_content_en',
            field=tinymce.models.HTMLField(blank=True, help_text='HTML email content (editable). Takes priority over template file.', null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='html_content_es',
            field=tinymce.models.HTMLField(blank=True, help_text='HTML email content (editable). Takes priority over template file.', null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='subject_en',
            field=models.CharField(help_text='Email subject line (supports template variables like {{ user.first_name }})', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='subject_es',
            field=models.CharField(help_text='Email subject line (supports template variables like {{ user.first_name }})', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='text_content_en',
            field=models.TextField(blank=True, help_text='Plain text email content. Takes priority over template file.', null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='text_content_es',
            field=models.TextField(blank=True, help_text='Plain text email content. Takes priority over template file.', null=True),
        ),
    ]
