# Generated by Django 5.2.10 on 2026-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_onboarding_email_username_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Test send from the email design studio. Excluded from the already-sent dedup guard and from DLQ retries — a failed test must never be re-dispatched as a real email.'),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='content_source',
            field=models.CharField(choices=[('code', 'Code'), ('design', 'Design')], default='code', help_text='Whether html_content was last authored in the visual designer or code mode. Code edits mark the stored design as stale for that language.', max_length=10),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='content_source_en',
            field=models.CharField(choices=[('code', 'Code'), ('design', 'Design')], default='code', help_text='Whether html_content was last authored in the visual designer or code mode. Code edits mark the stored design as stale for that language.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='content_source_es',
            field=models.CharField(choices=[('code', 'Code'), ('design', 'Design')], default='code', help_text='Whether html_content was last authored in the visual designer or code mode. Code edits mark the stored design as stale for that language.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='design_json',
            field=models.JSONField(blank=True, help_text='Block-editor document from the email design studio. The studio compiles it to html_content on save; the send path always renders html_content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='design_json_en',
            field=models.JSONField(blank=True, help_text='Block-editor document from the email design studio. The studio compiles it to html_content on save; the send path always renders html_content.', null=True),
        ),
        migrations.AddField(
            model_name='emailtype',
            name='design_json_es',
            field=models.JSONField(blank=True, help_text='Block-editor document from the email design studio. The studio compiles it to html_content on save; the send path always renders html_content.', null=True),
        ),
    ]
