# Generated by Django 5.2.8 on 2025-11-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_type',
            new_name='status',
        ),
    ]
