# Generated by Django 5.2.8 on 2025-11-30 18:40

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.product'),
        ),
        migrations.AddField(
            model_name='ordervalidationlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='combinedorder',
            constraint=models.UniqueConstraint(models.F('program'), django.db.models.functions.datetime.ExtractYear('created_at'), django.db.models.functions.datetime.ExtractWeek('created_at'), name='unique_program_per_week'),
        ),
    ]
