# Generated by Django 5.2.8 on 2025-12-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='combinedorder',
            name='unique_program_per_week',
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
