# Generated by Django 5.2.8 on 2025-11-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_account'),
        ('pantry', '0006_orderpacker_combinedorder_delete_orderpacked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedorder',
            name='packed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='combined_orders',
                to='pantry.OrderPacker',
            ),
        ),
        migrations.AlterField(
            model_name='combinedorder',
            name='program',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='combined_orders',
                to='lifeskills.program',
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='pantry.product',
            ),
        ),
    ]
