# Generated by Django 5.2.10 on 2026-01-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0002_alter_program_meeting_time'),
        ('orders', '0003_remove_combinedorder_unique_program_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='week',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='year',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='combinedorder',
            constraint=models.UniqueConstraint(fields=('program', 'week', 'year'), name='unique_program_per_week'),
        ),
    ]
