# Generated by Django 5.2.8 on 2025-11-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_combinedorder_packed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedorder',
            name='packed_by',
        ),
    ]
