# Generated by Django 5.2.10 on 2026-01-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0003_program_default_split_strategy'),
        ('orders', '0004_add_week_year_combined_order'),
        ('pantry', '0006_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='split_strategy',
            field=models.CharField(choices=[('none', 'None (Single Packer)'), ('fifty_fifty', '50/50 Split'), ('round_robin', 'Round Robin'), ('by_category', 'By Category')], default='none', help_text='Strategy used to split this combined order among packers', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='Whether this order has been included in a combined order'),
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summarized_data', models.JSONField(blank=True, default=dict, help_text="Aggregated product quantities for this packer's portion")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this packer is responsible for (for by_category strategy)', related_name='packing_lists', to='pantry.category')),
                ('combined_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='orders.combinedorder')),
                ('orders', models.ManyToManyField(blank=True, help_text='Orders assigned to this packer', related_name='packing_lists', to='orders.order')),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='pantry.orderpacker')),
            ],
            options={
                'verbose_name': 'Packing List',
                'verbose_name_plural': 'Packing Lists',
                'db_table': 'orders_packing_list',
            },
        ),
        migrations.CreateModel(
            name='PackingSplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this packer is responsible for', related_name='split_rules', to='pantry.category')),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_rules', to='pantry.orderpacker')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_split_rules', to='lifeskills.program')),
                ('subcategories', models.ManyToManyField(blank=True, help_text='Subcategories this packer is responsible for (overrides category)', related_name='split_rules', to='pantry.subcategory')),
            ],
            options={
                'verbose_name': 'Packing Split Rule',
                'verbose_name_plural': 'Packing Split Rules',
                'db_table': 'orders_packing_split_rule',
                'unique_together': {('program', 'packer')},
            },
        ),
    ]
