# Generated by Django 5.2.10 on 2026-01-17 21:16

from django.db import migrations


def mark_existing_combined_orders(apps, schema_editor):
    """
    Mark all orders that are already part of a CombinedOrder as is_combined=True.
    This is a data migration to ensure existing data reflects the new is_combined field.
    """
    Order = apps.get_model('orders', 'Order')
    CombinedOrder = apps.get_model('orders', 'CombinedOrder')
    
    # Get all order IDs that are in any combined order
    combined_order_ids = set()
    for combined_order in CombinedOrder.objects.all():
        combined_order_ids.update(combined_order.orders.values_list('id', flat=True))
    
    # Mark these orders as is_combined=True
    if combined_order_ids:
        Order.objects.filter(id__in=combined_order_ids).update(is_combined=True)


def reverse_mark_combined(apps, schema_editor):
    """
    Reverse migration - set all is_combined back to False.
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.all().update(is_combined=False)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_combinedorder_split_strategy_order_is_combined_and_more'),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_combined_orders,
            reverse_code=reverse_mark_combined,
        ),
    ]
