# Generated by Django 5.2.10 on 2026-01-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_mark_existing_combined_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_combined',
        ),
    ]
