# Generated by Django 5.2.10 on 2026-01-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_is_combined_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='go_fresh_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent on Go Fresh items in this order', max_digits=10),
        ),
    ]
