# Generated by Django 5.2.10 on 2026-02-13 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_update_hygiene_ratio_precision'),
        ('orders', '0008_add_go_fresh_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedOrderAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cart_snapshot', models.JSONField(help_text='[{product_id, product_name, quantity, price}]')),
                ('cart_hash', models.CharField(db_index=True, max_length=64)),
                ('total_attempted', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hygiene_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('full_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hygiene_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('program_pause_active', models.BooleanField(default=False)),
                ('program_pause_name', models.CharField(blank=True, max_length=255)),
                ('voucher_multiplier', models.IntegerField(default=1)),
                ('active_voucher_count', models.IntegerField(default=0)),
                ('validation_errors', models.JSONField(help_text='[{type, message, amount_over}]')),
                ('error_summary', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_attempts', to='account.participant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OrderValidationLog',
        ),
        migrations.AddIndex(
            model_name='failedorderattempt',
            index=models.Index(fields=['participant', '-created_at'], name='orders_fail_partici_46f973_idx'),
        ),
        migrations.AddIndex(
            model_name='failedorderattempt',
            index=models.Index(fields=['cart_hash', '-created_at'], name='orders_fail_cart_ha_015cc2_idx'),
        ),
    ]
