# Generated by Django 5.2.10 on 2026-03-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_failedorderattempt_delete_ordervalidationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pause_multiplier_at_creation',
            field=models.IntegerField(blank=True, help_text='Pause multiplier (2x or 3x) active when this order was created', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='program_pause_at_creation',
            field=models.CharField(blank=True, help_text='Name of program pause active when this order was created', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='failedorderattempt',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
