# Generated by Django 5.2.10 on 2026-05-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_pause_tracking_to_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_bypass_order_transitions', 'Can move orders between any active status (confirmed, packing, completed) regardless of normal forward-only flow')]},
        ),
    ]
