# Generated by Django 5.2.10 on 2026-07-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_bypass_transitions_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g., 'Tuesday/Wednesday Packing Run' or 'Week 12 Bulk Order'", max_length=255)),
                ('summarized_data', models.JSONField(blank=True, default=dict, help_text='Cached aggregated quantities: {category: {product: total_qty}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_orders', models.ManyToManyField(help_text='Which combined orders are included in this bulk list', related_name='warehouse_lists', to='orders.combinedorder')),
            ],
            options={
                'verbose_name': 'Warehouse Inventory List',
                'verbose_name_plural': 'Warehouse Inventory Lists',
                'ordering': ['-created_at'],
            },
        ),
    ]
