# Generated by Django 5.2.8 on 2025-11-30 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifeskills', '0002_alter_program_meeting_time'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='OrderPacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programs', models.ManyToManyField(blank=True, related_name='packers', to='lifeskills.program')),
            ],
            options={
                'db_table': 'food_orders_order_packer',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pantry.category')),
            ],
            options={
                'db_table': 'food_orders_subcategory',
            },
        ),
        migrations.CreateModel(
            name='ProductLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('limit', models.IntegerField(default=2, help_text='Maximum number of products allowed in this category per order.', validators=[django.core.validators.MinValueValidator(1)])),
                ('limit_scope', models.CharField(blank=True, choices=[('per_adult', 'Per Adult'), ('per_child', 'Per Child'), ('per_infant', 'Per Infant'), ('per_household', 'Per Household'), ('per_order', 'Per Order')], default='per_household', help_text='Scope of the limit: Adult, Child, Infant or Household.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='pantry.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_limits', to='pantry.subcategory')),
            ],
            options={
                'db_table': 'food_orders_product_limit',
            },
        ),
        
    ]
