# Generated by Django 5.2 on 2025-05-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caterogy',
            field=models.CharField(blank=True, choices=[('CF', 'Canned Fruits'), ('CB', 'Canned Beans'), ('CS', 'Canned Soup/Stew'), ('FM', 'Frozen Meat'), ('MM', 'Meal Makers'), ('CP', 'Cleaning Products'), ('SN', 'Snacks'), ('DY', 'Dairy'), ('BKS', 'Baking Supplies'), ('BEV', 'Beverages'), ('CND', 'Condiments'), ('CR', 'Cereal and Grains'), ('PH', 'Personal Hygiene'), ('HS', 'Household Supplies'), ('BI', 'Baby Items')], default='CF', max_length=20),
        ),
    ]
