# Generated by Django 5.2.8 on 2025-12-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_product_category_product_subcategory'),
    ]

    operations = [
    ]
