# Generated by Django 5.2.8 on 2025-12-02 02:08

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_enable_trigram_extension'),
    ]

    operations = [
        TrigramExtension(),
    ]
