# Generated by Django 5.2 on 2025-05-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_product_caterogy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caterogy',
            new_name='category',
        ),
    ]
