# Generated by Django 5.2 on 2025-05-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_rename_caterogy_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CombinedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Order', models.ManyToManyField(related_name='combined_orders', to='orders.order')),
                ('PackedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_packer', to='pantry.OrderPacker')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderPacked',
        ),
    ]
