# Generated by Django 5.2 on 2025-06-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_remove_order_products_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_voucher', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('half_voucher', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_balance', to='account.participant')),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='Participant',
            field=models.ManyToManyField(related_name='participant_voucher', to='account.accountbalance'),
        ),
    ]
