# Generated by Django 5.2.10 on 2026-04-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0009_add_sort_order_to_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='productlimit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_order', 'name']},
        ),
    ]
