# Generated by Django 5.2 on 2025-06-06 16:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0009_remove_order_total_amount_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_amount', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('child_amount', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('infant_modifier', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Voucher Settings',
            },
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='full_voucher',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='half_voucher',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='used',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 6, 16, 24, 29, 31980, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='infant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.accountbalance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_account_balance', to='lifeskills.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='Participant',
        ),
        migrations.AddField(
            model_name='voucher',
            name='Participant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='participant_voucher', to='lifeskills.participant'),
            preserve_default=False,
        ),
    ]
