# Generated by Django 5.2 on 2025-06-07 19:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0011_alter_order_status_alter_product_quantity_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Life', 'Life'), ('Grocery', 'Grocery')], default='Grocery', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
