# Generated by Django 5.2.10 on 2026-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0012_copy_catalog_text_to_english_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowInventoryAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(default=45, help_text="Alert when a product's quantity in stock is at or below this value.")),
                ('enabled', models.BooleanField(default=True, help_text='Enable low-inventory alert emails.')),
            ],
            options={
                'verbose_name': 'Low Inventory Alert Settings',
                'verbose_name_plural': 'Low Inventory Alert Settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_alerted_at',
            field=models.DateTimeField(blank=True, help_text='When the current low-stock episode was alerted. Set and cleared by the low-inventory beat task; cleared once stock recovers above the alert threshold.', null=True),
        ),
    ]
