# Generated by Django 5.2.10 on 2026-07-12 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pantry', '0013_low_inventory_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lowinventoryalertsettings',
            name='notify_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups whose members receive the low-inventory alert.', related_name='low_inventory_alert_settings', to='auth.group'),
        ),
        migrations.AddField(
            model_name='lowinventoryalertsettings',
            name='notify_users',
            field=models.ManyToManyField(blank=True, help_text='Additional individual users who receive the low-inventory alert.', related_name='low_inventory_alert_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
