# Generated by Django 5.2 on 2025-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0013_remove_voucher_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='balance',
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='adult_amount',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='child_amount',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='infant_modifier',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
