# Generated by Django 5.2.10 on 2026-08-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0015_seed_low_inventory_notify_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Automatically set to False when quantity_in_stock reaches 0 (see apps.pantry.utils.product_lifecycle). Restocking does not automatically reactivate it — flip this manually when ready.'),
        ),
    ]
