# Generated by Django 5.2 on 2025-06-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0019_alter_accountbalance_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifeskills.program'),
        ),
    ]
