# Generated by Django 5.2 on 2025-06-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0020_participant_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
