# Generated by Django 5.2 on 2025-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0021_voucher_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='notes',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
