# Generated by Django 5.2 on 2025-06-27 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0023_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='account.accountbalance'),
        ),
    ]
