# Generated by Django 5.2 on 2025-07-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0025_category_product_active_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanager',
            name='limit_scope',
            field=models.CharField(blank=True, choices=[('per_adult', 'Per Adult'), ('per_child', 'Per Child'), ('per_infant', 'Per Infant'), ('Per_household', 'Per Household')], default='per_household', help_text='Scope of the limit: Adult, Child, Infant or Household.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='category',
            field=models.ForeignKey(help_text='If category is selected limit will be enforced at the category level', on_delete=django.db.models.deletion.CASCADE, to='pantry.category'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='If Sub-Category is selected limit will be applied at the subcategory level', null=True, on_delete=django.db.models.deletion.CASCADE, to='pantry.subcategory'),
        ),
    ]
