# Generated by Django 5.2 on 2025-07-08 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0031_product_is_hygiene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combinedorder',
            old_name='Order',
            new_name='orders',
        ),
        migrations.RemoveField(
            model_name='combinedorder',
            name='PackedBy',
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='packed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packed_orders', to='pantry.OrderPacker'),
            preserve_default=False,
        ),
    ]
