# Generated by Django 5.2 on 2025-07-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0032_rename_order_combinedorder_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='program',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='combined_order', to='lifeskills.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combinedorder',
            name='packed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_orders', to='pantry.orderpacker'),
        ),
    ]
