# Generated by Django 5.2 on 2025-07-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0033_combinedorder_program_alter_combinedorder_packed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hygiene',
        ),
        migrations.AddField(
            model_name='product',
            name='create_user',
            field=models.BooleanField(default=False, help_text='If checked this will create a user account.', null=True),
        ),
    ]
