# Generated by Django 5.2 on 2025-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0034_remove_product_is_hygiene_product_create_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_user',
        ),
        migrations.AddField(
            model_name='participant',
            name='create_user',
            field=models.BooleanField(default=False, help_text='If checked this will create a user account.', null=True),
        ),
    ]
