# Generated by Django 5.2 on 2025-07-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0036_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
