# Generated by Django 5.2 on 2025-07-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0037_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifeskills.program'),
        ),
    ]
