# Generated by Django 5.2 on 2025-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0040_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_meat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='program',
            name='MeetingDay',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('life', 'Life'), ('grocery', 'Grocery')], default='grocery', max_length=20),
        ),
    ]
