# Generated by Django 5.2 on 2025-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0041_product_is_meat_product_weight_lbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmanager',
            name='limit_scope',
            field=models.CharField(blank=True, choices=[('per_adult', 'Per Adult'), ('per_child', 'Per Child'), ('per_infant', 'Per Infant'), ('per_household', 'Per Household'), ('per_order', 'Per Order')], default='per_household', help_text='Scope of the limit: Adult, Child, Infant or Household.', max_length=20, null=True),
        ),
    ]
