# Generated by Django 5.2 on 2025-08-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0044_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='infant',
        ),
        migrations.AddField(
            model_name='participant',
            name='diaper_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of Children in Diapers of Pull-Ups'),
        ),
    ]
