# Generated by Django 5.2 on 2025-08-22 14:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0046_alter_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='summarized_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderpacker',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='packers', to='lifeskills.program'),
        ),
        migrations.AlterField(
            model_name='combinedorder',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='combined_orders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='combinedorder',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_orders', to='pantry.orderpacker'),
        ),
        migrations.AlterField(
            model_name='combinedorder',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_orders', to='lifeskills.program'),
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='infant_modifier',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AddConstraint(
            model_name='combinedorder',
            constraint=models.UniqueConstraint(models.F('program'), django.db.models.functions.datetime.ExtractYear('created_at'), django.db.models.functions.datetime.ExtractWeek('created_at'), name='unique_program_per_week'),
        ),
    ]
