# Generated by Django 5.2 on 2025-09-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0057_alter_accountbalance_base_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpause',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programpause',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='programpause',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='programpause',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='programpause',
            name='is_active_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programpause',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programpause',
            name='pause_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programpause',
            name='pause_end_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programpause',
            name='pause_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programpause',
            name='pause_start_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packing', 'Packing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='The current status of the order. Options are: Pending New-Unpaid, Confirmed Paid, Packing, Complete Packed, or Cancelled.', max_length=20),
        ),
        migrations.AlterField(
            model_name='programpause',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
