# Generated by Django 5.2 on 2025-09-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0058_remove_programpause_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='program_pause_flag',
            field=models.BooleanField(default=False),
        ),
    ]
