# Generated by Django 5.2 on 2025-09-13 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0059_voucher_multiplier_voucher_program_pause_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpause',
            name='is_active_gate',
        ),
        migrations.RemoveField(
            model_name='programpause',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='programpause',
            name='pause_end_task_id',
        ),
        migrations.RemoveField(
            model_name='programpause',
            name='pause_start_task_id',
        ),
        migrations.AddField(
            model_name='programpause',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programpause',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='programpause',
            name='pause_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programpause',
            name='pause_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
