# Generated by Django 5.2 on 2025-11-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0068_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlog',
            name='applied_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='voucherlog',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='voucherlog',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
