# Generated by Django 5.2 on 2025-11-22 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0070_voucherlog_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('limit', models.IntegerField(default=2, help_text='Maximum number of products allowed in this category per order.', validators=[django.core.validators.MinValueValidator(1)])),
                ('limit_scope', models.CharField(blank=True, choices=[('per_adult', 'Per Adult'), ('per_child', 'Per Child'), ('per_infant', 'Per Infant'), ('per_household', 'Per Household'), ('per_order', 'Per Order')], default='per_household', help_text='Scope of the limit: Adult, Child, Infant or Household.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='combinedorder',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='combinedorder',
            name='packed_by',
        ),
        migrations.RemoveField(
            model_name='combinedorder',
            name='program',
        ),
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
