# Generated by Django 5.2 on 2025-11-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0071_productlimit_remove_combinedorder_orders_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervalidationlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ordervoucher',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_vouchers', to='orders.order'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='voucherlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='subcategory',
        ),
        migrations.AlterUniqueTogether(
            name='emaillog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pantry.category'),
        ),
        migrations.AlterField(
            model_name='program',
            name='MeetingDay',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=20),
        ),
        migrations.AddField(
            model_name='productlimit',
            name='category',
            field=models.OneToOneField(help_text='If category is selected, limit will be enforced at the category level.', on_delete=django.db.models.deletion.CASCADE, related_name='product_manager', to='pantry.category'),
        ),
        migrations.AddField(
            model_name='productlimit',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='If Sub-Category is selected limit will be applied at the subcategory level.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pantry.subcategory'),
        ),
        migrations.DeleteModel(
            name='CombinedOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='status',
        ),
    ]
