# Generated by Django 5.2.8 on 2025-11-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0072_alter_ordervalidationlog_order_and_more'),
        ('orders', '0003_alter_order_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='account',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordervalidationlog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordervalidationlog',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='ordervalidationlog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordervalidationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordervoucher',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordervoucher',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='assigned_coach',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='program',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voucherlog',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voucherlog',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='voucherlog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='voucherlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='VoucherSetting',
        ),
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='OrderValidationLog',
        ),
        migrations.DeleteModel(
            name='OrderVoucher',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='VoucherLog',
        ),
    ]
