# Generated by Django 5.2.8 on 2025-11-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0073_remove_accountbalance_participant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifeskillsCoach',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramPause',
        ),
        migrations.AlterField(
            model_name='orderpacker',
            name='programs',
            field=models.ManyToManyField(
                blank=True, related_name='packers', to='lifeskills.program'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='pantry.category',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='pantry.subcategory',
            ),
        ),
        migrations.AlterField(
            model_name='productlimit',
            name='category',
            field=models.OneToOneField(
                help_text=(
                    'If category is selected, limit will be enforced at the '
                    'category level.'
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name='product_manager',
                to='pantry.category',
            ),
        ),
        migrations.AlterField(
            model_name='productlimit',
            name='subcategory',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'If Sub-Category is selected limit will be applied at the '
                    'subcategory level.'
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='pantry.subcategory',
            ),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subcategories',
                to='pantry.category',
            ),
        ),
    ]
