# Generated by Django 5.2.8 on 2025-11-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0074_delete_lifeskillscoach_delete_program_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='food_orders_category',
        ),
        migrations.AlterModelTable(
            name='orderpacker',
            table='food_orders_orderpacker',
        ),
        migrations.AlterModelTable(
            name='product',
            table='food_orders_product',
        ),
        migrations.AlterModelTable(
            name='productlimit',
            table='food_orders_productlimit',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='food_orders_subcategory',
        ),
    ]
