# Generated by Django 5.2.8 on 2025-11-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0075_alter_category_table_alter_orderpacker_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='pantry_category',
        ),
    ]
