# Generated by Django 5.2.8 on 2025-11-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0077_create_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
