# Generated by Django 5.2.8 on 2025-11-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0078_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='food_orders_category',
        ),
    ]
