# Generated by Django 5.2.8 on 2025-11-30 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0079_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlimit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='pantry.category'),
        ),
        migrations.AlterField(
            model_name='productlimit',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_limits', to='pantry.subcategory'),
        ),
    ]
