# Generated by Django 5.2.8 on 2025-11-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0080_alter_productlimit_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productlimit',
            table=None,
        ),
    ]
