# Generated by Django 5.2.8 on 2025-11-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0081_alter_productlimit_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlimit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productlimit',
            name='subcategory',
        ),
        migrations.AlterModelTable(
            name='orderpacker',
            table=None,
        ),
    ]
