# Generated by Django 5.2.8 on 2025-11-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0082_remove_productlimit_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlimit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='pantry.category'),
        ),
        migrations.AddField(
            model_name='productlimit',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_limits', to='pantry.subcategory'),
        ),
    ]
