coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "apps/*/migrations"
  - "apps/*/tests"
  - "apps/*/admin.py"
  - "apps/*/apps.py"
  - "*/conftest.py"
