# Generated by Django 5.2.8 on 2025-12-03 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWindowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before_class', models.PositiveIntegerField(default=24, help_text='Hours before class time when ordering window opens (1-168 hours, default 24)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable order window restrictions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Window Setting',
                'verbose_name_plural': 'Order Window Settings',
            },
        ),
    ]
