# Generated by Django 5.2.8 on 2025-12-04 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwindowsettings',
            name='hours_before_close',
            field=models.PositiveIntegerField(default=0, help_text='Hours before class time when ordering window closes (0-168 hours, default 0 = closes at class time)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
    ]
