# Generated by Django 5.2.10 on 2026-01-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderwindowsettings_hours_before_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email_default', models.EmailField(blank=True, help_text="Default from email address. Leave blank to use Django's DEFAULT_FROM_EMAIL setting.", max_length=254)),
                ('reply_to_default', models.EmailField(default='it@loveyourneighbor.org', help_text='Default reply-to email address for all emails', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Setting',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
