# Generated by Django 5.2.10 on 2026-01-15 02:21

from django.db import migrations


def seed_email_settings(apps, schema_editor):
    """Create the singleton EmailSettings instance with defaults."""
    EmailSettings = apps.get_model('core', 'EmailSettings')
    
    # Only create if it doesn't exist
    if not EmailSettings.objects.exists():
        EmailSettings.objects.create(
            pk=1,
            from_email_default='',  # Will fall back to Django's DEFAULT_FROM_EMAIL
            reply_to_default='it@loveyourneighbor.org',
        )


def reverse_seed(apps, schema_editor):
    """Remove the seeded EmailSettings instance."""
    EmailSettings = apps.get_model('core', 'EmailSettings')
    EmailSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailsettings'),
    ]

    operations = [
        migrations.RunPython(seed_email_settings, reverse_seed),
    ]
