# Generated by Django 5.2.10 on 2026-01-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Love Your Neighbor', help_text='Organization name to display on printed orders', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Upload organization logo (displayed on printed orders)', null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branding Setting',
                'verbose_name_plural': 'Branding Settings',
            },
        ),
    ]
