# Generated by Django 5.2.10 on 2026-02-03 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brandingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_amount', models.DecimalField(decimal_places=2, default=1.0, help_text="Dollar amount over budget allowed as 'grace' for financial literacy learning (default $1.00)", max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('grace_enabled', models.BooleanField(default=True, help_text='Enable/disable grace allowance feature')),
                ('grace_message', models.TextField(default='This helps you practice staying within budget', help_text='Educational message displayed when user is within grace allowance')),
                ('rules_version', models.CharField(blank=True, editable=False, help_text='MD5 hash of business rules (auto-generated)', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Program Setting',
                'verbose_name_plural': 'Program Settings',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1976d2', help_text='Primary theme color (hex format, e.g., #1976d2)', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', help_text='Secondary theme color (hex format, e.g., #dc004e)', max_length=7)),
                ('app_name', models.CharField(default='Basketful', help_text='Application name displayed in participant frontend', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo displayed on participant login page', null=True, upload_to='theme/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for participant frontend (32x32 or 16x16)', null=True, upload_to='theme/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Theme Setting',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
