# Generated by Django 5.2.10 on 2026-04-16 01:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_programsettings_themesettings'),
        ('lifeskills', '0006_programpause_resync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOrderWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before_class', models.PositiveIntegerField(blank=True, help_text='Override: hours before class the window opens. Leave blank to use the global default.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('hours_before_close', models.PositiveIntegerField(blank=True, help_text='Override: hours before class the window closes. Leave blank to use the global default.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('enabled', models.BooleanField(blank=True, help_text="Override: enable/disable this program's order window. Leave blank to use the global default.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_window', to='lifeskills.program')),
            ],
            options={
                'verbose_name': 'Program Order Window Override',
                'verbose_name_plural': 'Program Order Window Overrides',
            },
        ),
        migrations.CreateModel(
            name='ProgramWindowOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_status', models.CharField(choices=[('open', 'Force Open'), ('closed', 'Force Closed')], max_length=10)),
                ('expires_at', models.DateTimeField(help_text='Override is automatically ignored after this time.')),
                ('reason', models.TextField(blank=True, help_text='Why is this override active? Shown to other staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='window_override', to='lifeskills.program')),
            ],
            options={
                'verbose_name': 'Program Window Override',
                'verbose_name_plural': 'Program Window Overrides',
            },
        ),
    ]
