# Generated by Django 5.2.10 on 2026-07-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_programorderwindow_programwindowoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsettings',
            name='grace_message_en',
            field=models.TextField(default='This helps you practice staying within budget', help_text='Educational message displayed when user is within grace allowance', null=True),
        ),
        migrations.AddField(
            model_name='programsettings',
            name='grace_message_es',
            field=models.TextField(default='This helps you practice staying within budget', help_text='Educational message displayed when user is within grace allowance', null=True),
        ),
    ]
