# Generated by Django 5.2.10 on 2026-07-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_copy_grace_message_to_english_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='backend_domain',
            field=models.CharField(blank=True, help_text='Domain for backend links such as password reset (e.g. api.example.org). Leave blank to use the DOMAIN_NAME environment setting.', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='participant_frontend_url',
            field=models.URLField(blank=True, help_text='Participant app URL used in emails (e.g. https://shop.example.org). Leave blank to use the PARTICIPANT_FRONTEND_URL environment setting.'),
        ),
    ]
