"""
Django settings for lyn_app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
from pathlib import Path
from datetime import timedelta
import sys
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)
env_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_path):
    env.read_env(env_path)

SECRET_KEY = env('SECRET_KEY')
DOMAIN_NAME = env('DOMAIN_NAME', default='localhost')
HASHIDS_SALT = env('HASHIDS_SALT', default='default-salt-change-in-production')
HASHIDS_MIN_LENGTH = env.int('HASHIDS_MIN_LENGTH', default=10)

ENVIRONMENT = env('DJANGO_ENV', default='dev')
DEBUG = env.bool('DEBUG', default=False)

# Cookie settings based on environment
if ENVIRONMENT == 'prod':
    AUTH_COOKIE_SECURE = True
    AUTH_COOKIE_SAMESITE = 'Lax'
    AUTH_COOKIE_DOMAIN = env('COOKIE_DOMAIN', default=None)
else:
    AUTH_COOKIE_SECURE = False
    AUTH_COOKIE_SAMESITE = 'Lax'
    AUTH_COOKIE_DOMAIN = None

CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = env.bool(
    "CELERY_TASK_EAGER_PROPAGATES", default=False
)

# Override for test mode - detect pytest
if 'pytest' in sys.modules or any('pytest' in arg for arg in sys.argv):
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


environ.Env.read_env()  # reads from .env

# Set defaults based on environment
if ENVIRONMENT == 'prod':
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
    # Use Mailgun HTTP API (bypasses SMTP port restrictions)
    EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
    ANYMAIL = {
        'MAILGUN_API_KEY': env('MAILGUN_API_KEY'),
        'MAILGUN_SENDER_DOMAIN': env('MAILGUN_SENDER_DOMAIN', default='mg.lovewm.org'),
    }
    DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='hello@lovewm.org')
else:  # dev/local
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DATABASES = {
    'default': env.db('DATABASE_URL')
}

# LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
    'django.request': {
        'handlers': ['console'],
        'level': 'ERROR',
        'propagate': False,
    },
}

# AWS / Linode S3 storage toggle
USE_S3 = env.bool('USE_S3', default=False)

if USE_S3:
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-ord-1")

    # This endpoint URL points to Linode's S3-compatible object storage
    AWS_S3_ENDPOINT_URL = env(
        "AWS_S3_ENDPOINT_URL", default="https://us-ord-1.linodeobjects.com"
    )

    # Custom domain for serving static and media files
    AWS_S3_CUSTOM_DOMAIN = env(
        "AWS_S3_CUSTOM_DOMAIN",
        default=f"{AWS_STORAGE_BUCKET_NAME}.us-ord-1.linodeobjects.com"
    )

    STATICFILES_LOCATION = env("STATICFILES_LOCATION", default="static")
    MEDIAFILES_LOCATION = env("MEDIAFILES_LOCATION", default="media")

    STORAGES = {
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "custom_domain": AWS_S3_CUSTOM_DOMAIN,
                "location": STATICFILES_LOCATION,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "querystring_auth": False,
            },
        },
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "custom_domain": AWS_S3_CUSTOM_DOMAIN,
                "location": MEDIAFILES_LOCATION,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
            },
        },
    }

    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATICFILES_LOCATION}/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIAFILES_LOCATION}/"

else:
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    ]

    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Add the apps directory to the Python path
sys.path.append(os.path.join(BASE_DIR, 'apps'))

# Installed apps
INSTALLED_APPS = [
    # Local apps - listed first to override Django admin templates
    'apps.pantry.apps.PantryConfig',
    # Django contrib apps
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.auth',
    # Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    # Third-party
    'django_bootstrap5',
    'django_recaptcha',
    'django_celery_beat',
    'anymail',
    'storages',
    'tinymce',
    # Other local apps
    'apps.api',
    'apps.log',
    'apps.lifeskills',
    'apps.voucher',
    'apps.account',
    'apps.orders',
    'core',
]

# Middleware configuration
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'core.middleware.GlobalErrorMiddleware',
]

# URL Configuration
ROOT_URLCONF = 'core.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add your template directories here if any
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI Application
WSGI_APPLICATION = 'core.wsgi.application'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'
TIME_FORMAT = 'g:i A'

USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# reCAPTCHA keys
RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_PUBLIC_KEY', default='test-public-key')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY', default='test-private-key')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Celery Settings
CELERY_BROKER_URL = env(
    'CELERY_BROKER_URL', default='redis://localhost:6379/0'
)
CELERY_RESULT_BACKEND = env(
    'CELERY_RESULT_BACKEND', default='redis://localhost:6379/0'
)

# Redis connection retry settings for handling failovers
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 30,
    'socket_connect_timeout': 30,
    'retry_on_timeout': True,
}

CELERY_BEAT_SCHEDULE = {
    'create_weekly_combined_orders': {
        'task': 'orders.tasks.create_weekly_combined_orders',
    },
    'cleanup-expired-pause-flags': {
        'task': 'apps.lifeskills.tasks.program_pause.cleanup_expired_pause_flags',
        'schedule': crontab(hour=3, minute=0),  # Daily at 3 AM
    },
}

SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap preview anchor '
               'searchreplace visualblocks code fullscreen insertdatetime '
               'media table paste code help wordcount',
    'toolbar': 'undo redo | formatselect | bold italic backcolor | '
               'alignleft aligncenter alignright alignjustify | '
               'bullist numlist outdent indent | removeformat | code | help',
    'content_style': 'body { font-family: -apple-system, BlinkMacSystemFont, '
                     '"Segoe UI", Roboto, Helvetica, Arial, sans-serif; '
                     'font-size: 14px; }',
}

# =============================================================================
# Django REST Framework Configuration
# =============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.account.api.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '100/minute',
        'login': '5/minute',
        'order_submission': '3/minute',  # Order submission rate limiting
    },
    'DEFAULT_PAGINATION_CLASS': 'apps.api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    # Cookie settings for httpOnly cookies
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SECURE': AUTH_COOKIE_SECURE,
    'AUTH_COOKIE_SAMESITE': AUTH_COOKIE_SAMESITE,
    'AUTH_COOKIE_PATH': '/',
}

# CORS Settings - React frontend origins
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
])
CORS_ALLOW_CREDENTIALS = True

# Django Bootstrap 5 Configuration - Serve locally to avoid CSP violations
BOOTSTRAP5 = {
    'css_url': {
        'url': '/static/bootstrap/bootstrap.min.css',
    },
    'javascript_url': {
        'url': '/static/bootstrap/bootstrap.bundle.min.js',
    },
}

# API Documentation (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Basketful API',
    'DESCRIPTION': 'REST API for Basketful food pantry and voucher management',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v1/',
}

