# Generated by Django 5.2.8 on 2025-11-25 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_amount', models.DecimalField(decimal_places=1, default=20, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('child_amount', models.DecimalField(decimal_places=1, default=12.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('infant_modifier', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Voucher Settings',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('voucher_type', models.CharField(choices=[('life', 'Life'), ('grocery', 'Grocery')], default='grocery', max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='pending', editable=False, max_length=20)),
                ('program_pause_flag', models.BooleanField(default=False)),
                ('multiplier', models.IntegerField(default=1, editable=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='account.accountbalance')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_vouchers', to='orders.order')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_applications', to='voucher.voucher')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
