# Generated by Django 5.2.8 on 2025-11-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='assigned_coach',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customers',
                to='lifeskills.lifeskillscoach',
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='program',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='lifeskills.program',
            ),
        ),
    ]
