# Generated by Django 5.2.10 on 2026-01-30 00:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def seed_go_fresh_settings(apps, schema_editor):
    """
    Create the singleton GoFreshSettings instance with defaults.
    Also check if Go Fresh category exists and warn if missing.
    """
    GoFreshSettings = apps.get_model('account', 'GoFreshSettings')
    Category = apps.get_model('pantry', 'Category')
    
    # Check if Go Fresh category exists
    if not Category.objects.filter(name__iexact='Go Fresh').exists():
        print("⚠️  Warning: 'Go Fresh' category not found.")
        print("   Please create it in the Django admin under Pantry > Categories.")
    
    # Create GoFreshSettings singleton if it doesn't exist
    if not GoFreshSettings.objects.exists():
        GoFreshSettings.objects.create(
            pk=1,
            small_household_budget=Decimal('10.00'),
            medium_household_budget=Decimal('20.00'),
            large_household_budget=Decimal('25.00'),
            small_threshold=2,
            large_threshold=6,
            enabled=True
        )
        print("✓ GoFreshSettings created with default values")


def reverse_seed_go_fresh_settings(apps, schema_editor):
    """Remove the GoFreshSettings singleton."""
    GoFreshSettings = apps.get_model('account', 'GoFreshSettings')
    GoFreshSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_populate_customer_numbers'),
        ('pantry', '0001_initial'),  # Need pantry for Category check
    ]

    operations = [
        migrations.CreateModel(
            name='GoFreshSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_household_budget', models.DecimalField(decimal_places=2, default=10.0, help_text='Budget for households with 1-2 people (default: $10.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('medium_household_budget', models.DecimalField(decimal_places=2, default=20.0, help_text='Budget for households with 3-5 people (default: $20.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('large_household_budget', models.DecimalField(decimal_places=2, default=25.0, help_text='Budget for households with 6+ people (default: $25.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('small_threshold', models.PositiveIntegerField(default=2, help_text='Household size up to this number gets small budget (default: 2)', validators=[django.core.validators.MinValueValidator(1)])),
                ('large_threshold', models.PositiveIntegerField(default=6, help_text='Household size at or above this gets large budget (default: 6)', validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable Go Fresh budget feature')),
            ],
            options={
                'verbose_name': 'Go Fresh Settings',
                'verbose_name_plural': 'Go Fresh Settings',
                'permissions': [('can_view_go_fresh_analytics', 'Can view Go Fresh analytics dashboard')],
            },
        ),
        migrations.RunPython(seed_go_fresh_settings, reverse_seed_go_fresh_settings),
    ]
