# Generated by Django 5.2.8 on 2025-11-29 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_active_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='base_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
