# Generated by Django 5.2.10 on 2026-02-12 03:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_add_go_fresh_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HygieneSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hygiene_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.3333'), help_text='Ratio of available balance allocated for hygiene (e.g., 0.3333 = 1/3)', max_digits=5)),
                ('enabled', models.BooleanField(default=True, help_text='Enable hygiene balance calculation')),
            ],
            options={
                'verbose_name': 'Hygiene Settings',
                'verbose_name_plural': 'Hygiene Settings',
            },
        ),
    ]
