# Generated by Django 5.2.8 on 2025-11-30 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountbalance_base_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='base_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
