# Generated by Django 5.2.10 on 2026-02-12 03:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_add_hygiene_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hygienesettings',
            name='hygiene_ratio',
            field=models.DecimalField(decimal_places=28, default=Decimal('0.3333333333333333333333333333'), help_text='Ratio of available balance allocated for hygiene (e.g., 0.333... = 1/3)', max_digits=30),
        ),
    ]
