# Generated by Django 5.2.10 on 2026-03-15 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_update_hygiene_ratio_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='base_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
