# Generated by Django on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_fix_base_balance_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when participant was archived', null=True),
        ),
    ]
