# Generated by Django 5.2.10 on 2026-05-02 00:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_add_archived_at_to_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='Preferred language for communications and welcome card', max_length=5),
        ),
        migrations.AlterField(
            model_name='gofreshsettings',
            name='large_household_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Budget for households with 6+ people (default: $25.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gofreshsettings',
            name='medium_household_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Budget for households with 3-5 people (default: $20.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gofreshsettings',
            name='small_household_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Budget for households with 1-2 people (default: $10.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='BulkCreateBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.JSONField()),
                ('celery_task_ids', models.JSONField(default=list)),
                ('email_grace_seconds', models.IntegerField(default=0)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_create_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Create Batch',
                'verbose_name_plural': 'Bulk Create Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
