# Generated by Django 5.2.10 on 2026-07-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_backfill_hygiene_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='create_user',
            field=models.BooleanField(default=True, help_text='If checked this will create a user account.'),
        ),
    ]
