# Generated by Django 5.2.10 on 2026-07-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_default_create_user_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='create_user',
        ),
    ]
