# Generated by Django 5.2.10 on 2026-07-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_create_user_field'),
        ('lifeskills', '0008_coach_programs_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='assigned_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='lifeskills.lifeskillscoach'),
        ),
    ]
