# Generated by Django 5.2 on 2025-05-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0002_order_status_program_meetingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
