# Generated by Django 5.2 on 2025-06-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0008_accountbalance_voucher_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='order',
        ),
    ]
