# Generated by Django 5.2 on 2025-06-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0015_classcalendar_remove_order_participant_order_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassCalendar',
            new_name='ProgramPause',
        ),
    ]
