# Generated by Django 5.2 on 2025-06-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_orders.participant'),
        ),
    ]
