# Generated by Django 5.2 on 2025-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0022_alter_voucher_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
