# Generated by Django 5.2 on 2025-07-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0038_alter_participant_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone_number',
        ),
    ]
