# Generated by Django 5.2 on 2025-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0051_alter_vouchersetting_adult_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
