# Generated by Django 5.2 on 2025-08-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0052_participant_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='MeetingDay',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')]),
        ),
    ]
