# Generated by Django 5.2 on 2025-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0060_remove_programpause_is_active_gate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpause',
            name='pause_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='programpause',
            name='pause_start',
            field=models.DateTimeField(),
        ),
    ]
