# Generated by Django 5.2 on 2025-09-13 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0061_alter_programpause_pause_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
