# Generated by Django 5.2 on 2025-10-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0064_ordervoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('consumed', 'Consumed')], default='pending', max_length=20),
        ),
    ]
