# Generated by Django 5.2 on 2025-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0065_voucher_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='multiplier',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('consumed', 'Consumed')], default='pending', editable=False, max_length=20),
        ),
    ]
