# Generated by Django 5.2 on 2025-10-19 20:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0066_alter_voucher_multiplier_alter_voucher_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(
                default='ORD-00001',
                editable=False,
                max_length=20,
                unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='success_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_type',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('packing', 'Packing'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled')
                ],
                default='pending',
                help_text='The current status of the order.',
                max_length=20
            ),
        ),
    ]
