# Generated by Django 5.2.8 on 2025-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='meeting_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
