# Generated by Django 5.2.10 on 2026-01-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0002_alter_program_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='default_split_strategy',
            field=models.CharField(choices=[('none', 'None (Single Packer)'), ('fifty_fifty', '50/50 Split'), ('round_robin', 'Round Robin'), ('by_category', 'By Category')], default='none', help_text='Default strategy for splitting combined orders among packers', max_length=20),
        ),
    ]
