# Generated by Django 5.2.10 on 2026-02-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0003_program_default_split_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='meeting_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
