# Generated by Django 5.2.10 on 2026-02-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0004_alter_program_meeting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpause',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programpause',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
