# Generated by Django 5.2.10 on 2026-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeskills', '0007_lifeskillscoach_user_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeskillscoach',
            name='program',
        ),
        migrations.AddField(
            model_name='lifeskillscoach',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Programs this coach is assigned to', related_name='coaches', to='lifeskills.program'),
        ),
    ]
