# Generated by Django 5.2 on 2025-06-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0012_voucher_voucher_type_alter_accountbalance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='Participant',
        ),
    ]
