# Generated by Django 5.2 on 2025-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0017_alter_order_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('CF', 'Canned Fruits'), ('CB', 'Canned Beans'), ('CS', 'Canned Soup/Stew'), ('FM', 'Frozen Meat'), ('MM', 'Meal Makers'), ('CPM', 'Canned Pasta/Meat'), ('SN', 'Snacks'), ('DY', 'Dairy'), ('BKS', 'Baking Supplies'), ('BEV', 'Beverages'), ('CND', 'Condiments'), ('CR', 'Cereal and Grains'), ('PH', 'Personal Hygiene'), ('CP', 'Cleaning Products'), ('HS', 'Household Supplies'), ('BI', 'Baby Items')], default='CF', max_length=20),
        ),
    ]
