# Generated by Django 5.2 on 2025-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0030_alter_product_category_alter_productmanager_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hygiene',
            field=models.BooleanField(default=False, help_text='Is this product a hygiene item?'),
        ),
    ]
