# Generated by Django 5.2 on 2025-08-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0045_remove_participant_infant_participant_diaper_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
