# Generated by Django 5.2 on 2025-08-21 00:43

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0047_combinedorder_summarized_data_orderpacker_programs_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='combinedorder',
            constraint=models.UniqueConstraint(models.F('program'), django.db.models.functions.datetime.ExtractYear('created_at'), django.db.models.functions.datetime.ExtractWeek('created_at'), name='unique_program_per_week'),
        ),
    ]
