# Generated by Django 5.2 on 2025-08-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0049_remove_combinedorder_orders_order_combined_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchersetting',
            name='infant_modifier',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
