# Generated by Django 5.2 on 2025-08-25 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0050_alter_vouchersetting_adult_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchersetting',
            name='adult_amount',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='child_amount',
            field=models.DecimalField(decimal_places=1, default=12.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vouchersetting',
            name='infant_modifier',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
