# Generated by Django 5.2 on 2025-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0054_combinedorder_is_parent_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_type',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('packing', 'Packing'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled')
                ],
                default='pending',
                help_text='The current status of the order. Options are: Pending New-Unpaid, Confirmed Paid , Packing, Complete Packed, or Cancelled.',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='allergy',
            field=models.CharField(
                blank=True,
                default='None',
                max_length=100,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='create_user',
            field=models.BooleanField(
                default=False,
                help_text='If checked this will create a user account.'
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='diaper_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Count of Children in Diapers or Pull-Ups'
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
