# Generated by Django 5.2 on 2025-08-28 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0055_alter_order_status_type_alter_participant_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='base_balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
