# Generated by Django 5.2 on 2025-10-11 19:38

import django_ulid.models
from django.db import migrations, models
from django.utils.timezone import now

def assign_order_numbers(apps, schema_editor):
    Order = apps.get_model('food_orders', 'Order')
    today_str = now().strftime("%Y%m%d")
    prefix = "ORD"
    sequence = 1

    for order in Order.objects.all():
        order_number = f"{prefix}-{today_str}-{sequence:06d}"
        order.order_number = order_number
        order.save(update_fields=['order_number'])
        sequence += 1

class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0066_alter_voucher_multiplier_alter_voucher_state'),
    ]

    operations = [
        # Add order_number field temporarily allowing null
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),

        # Populate existing rows
        migrations.RunPython(assign_order_numbers),

        # Make order_number unique and non-null
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, null=False),
        ),

        # Add success_viewed boolean field
        migrations.AddField(
            model_name='order',
            name='success_viewed',
            field=models.BooleanField(default=False),
        ),

        # Add ULIDField as temporary primary key
        migrations.AddField(
            model_name='order',
            name='new_id',
            field=django_ulid.models.ULIDField(serialize=False),
        ),

        # Remove the old id field safely
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),

        # Rename new_id back to id as the primary key
        migrations.RenameField(
            model_name='order',
            old_name='new_id',
            new_name='id',
        ),

        # Alter status_type field (unchanged)
        migrations.AlterField(
            model_name='order',
            name='status_type',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('packing', 'Packing'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled')
                ],
                default='pending',
                help_text='The current status of the order.',
                max_length=20
            ),
        ),
    ]
