# Generated by Django 5.2 on 2025-10-11 19:38

import django_ulid.models
from django.db import migrations, models
from food_orders.models import Order

def assign_order_numbers(apps, schema_editor):
    order = apps.get_model('food_orders', 'Order')
    for order in Order.objects.all():
        order.order_number = Order.generate_order_number
        order.save(update_fields=['order_number'])

class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0066_alter_voucher_multiplier_alter_voucher_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField( editable=False, max_length=20, null=True),
        ),
                
        migrations.RunPython(assign_order_numbers),

        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField( editable=False, max_length=20, null=False,unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='success_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='new_id',
            field=django_ulid.models.ULIDField(serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packing', 'Packing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='The current status of the order.', max_length=20),
        ),
    ]
