# Generated by Django 5.2 on 2025-11-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_orders', '0069_voucherlog_applied_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlog',
            name='remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
